name: ShopAddon

main: me.tWizT3d_dreaMr.ShopAddon.main
version: 1.4.2
author: tWizT3d_dreaMr
api-version: 1.19
depend: [ Shop ]
softdepend: [ WorldGuard ]
commands:
   sa:
      description: checks shop signs log
      usage: sa check <page>
   filterall:
      description: filterall shops
      usage: filterall
   ShopNotifications:
      description: Changes your shop notification settings
      usage: ShopNotifications
   SASQLConversion:
      description: Converts my logging to official logging
      usage: SASQLConversion