name: ShopAddon

main: me.tWizT3d_dreaMr.ShopAddon.main
version: 1.2.1
author: tWizT3d_dreaMr
api-version: 1.17
depend: [ Shop ]
softdepend: [ WorldGuard ]
commands:
   sa:
      description: checks shop signs log
      usage: sa check <page>
   ShopNotifications:
      description: Changes your shop notification settings
      usage: ShopNotifications