name: ShopAddon

main: me.tWizT3d_dreaMr.ShopAddon.main
version: 1.0
author: tWizT3d_dreaMr
api-version: 1.16
depend: [ Shop ]
commands:
   sa:
      description: checks shop signs log
      usage: sa check <page>